In [2]:
import numpy as np
import pandas as pd

In [1]:
from google.colab import files
Uploaded = files.upload()

Saving ultimate_anime_dataset.csv to ultimate_anime_dataset.csv

In [6]:
credit = pd.read_csv('ultimate_anime_dataset.csv')
Anime_df = pd.read_csv('ultimate_anime_dataset.csv')

In [7]:
credit.head()

,title,english_title,romaji_title,genres,rating_anilist,rating_mal,episodes,status,format,season,...,source_material,popularity_anilist,mal_members,mal_rank,cover_image_url,start_date,end_date,duration_per_ep,age_rating,mal_id
0,Attack on Titan,Attack on Titan,Shingeki no Kyojin,Action | Drama | Fantasy | Mystery,8.5,8.57,25.0,FINISHED,TV,SPRING,...,MANGA,1000051,4367640.0,127.0,https://s4.anilist.co/file/anilistcdn/media/an...,2013-04-07,2013-09-28,24.0,R - 17+ (violence & profanity),16498.0
1,Demon Slayer: Kimetsu no Yaiba,Demon Slayer: Kimetsu no Yaiba,Kimetsu no Yaiba,Action | Adventure | Drama | Fantasy | Superna...,8.3,8.40,26.0,FINISHED,TV,SPRING,...,MANGA,946267,3455059.0,232.0,https://s4.anilist.co/file/anilistcdn/media/an...,2019-04-06,2019-09-28,24.0,R - 17+ (violence & profanity),38000.0
2,JUJUTSU KAISEN,JUJUTSU KAISEN,Jujutsu Kaisen,Action | Drama | Supernatural,8.4,8.50,24.0,FINISHED,TV,FALL,...,MANGA,915193,3043711.0,166.0,https://s4.anilist.co/file/anilistcdn/media/an...,2020-10-03,2021-03-27,24.0,R - 17+ (violence & profanity),40748.0
3,Death Note,Death Note,DEATH NOTE,Mystery | Psychological | Supernatural | Thriller,8.4,8.62,37.0,FINISHED,TV,FALL,...,MANGA,911296,4305882.0,99.0,https://s4.anilist.co/file/anilistcdn/media/an...,2006-10-04,2007-06-27,23.0,R - 17+ (violence & profanity),1535.0
4,My Hero Academia,My Hero Academia,Boku no Hero Academia,Action | Adventure | Comedy,7.7,7.83,13.0,FINISHED,TV,SPRING,...,MANGA,834900,3310857.0,1109.0,https://s4.anilist.co/file/anilistcdn/media/an...,2016-04-03,2016-06-26,24.0,PG-13 - Teens 13 or older,31964.0

In [9]:
Anime_df.isnull().sum().sum()

np.int64(1394)

In [40]:
Anime_df.isnull().sum()

title                 0
english_title         0
romaji_title          0
genres                0
rating_anilist        0
rating_mal            0
episodes              0
status                0
format                0
season                0
year                  0
synopsis              0
studio                0
source_material       0
popularity_anilist    0
mal_members           0
mal_rank              0
cover_image_url       0
start_date            0
end_date              0
duration_per_ep       0
age_rating            0
mal_id                0
dtype: int64

In [12]:
Anime_df['english_title'] = Anime_df['english_title'].fillna(Anime_df['title'])

In [13]:
Anime_df['english_title'].isnull().sum()

np.int64(0)

In [14]:
Anime_df['genres'] = Anime_df['genres'].fillna('Unknown')

In [15]:
Anime_df['genres'].isnull().sum()

np.int64(0)

In [21]:
Anime_df['rating_anilist'] = Anime_df['rating_anilist'].fillna(Anime_df['rating_anilist'].median())
Anime_df['rating_mal'] = Anime_df['rating_mal'].fillna(Anime_df['rating_mal'].median())
Anime_df['episodes'] = Anime_df['episodes'].fillna(1)
Anime_df['format'] = Anime_df['format'].fillna("unavailable")

In [27]:
Anime_df = Anime_df.dropna(subset=['season'])

In [29]:
Anime_df = Anime_df.dropna(subset=['year'])

In [30]:
Anime_df = Anime_df.dropna(subset=['synopsis'])

In [31]:
Anime_df['studio'] = Anime_df['studio'].fillna("unknown")

In [32]:
Anime_df['source_material'] = Anime_df['source_material'].fillna("unknown")

In [33]:
Anime_df = Anime_df.dropna(subset=['mal_members'])

In [35]:
max_rank = Anime_df['mal_rank'].max()
fill_value = max_rank + 1

Anime_df['mal_rank'] = Anime_df['mal_rank'].fillna(fill_value)

In [36]:
Anime_df['start_date'] = Anime_df['start_date'].fillna("Unknown")
Anime_df['end_date'] = Anime_df['end_date'].fillna("Ongoing")

In [38]:
mode_duration = Anime_df['duration_per_ep'].mode()[0]
Anime_df['duration_per_ep'] = Anime_df['duration_per_ep'].fillna(mode_duration)

In [41]:
Anime_df.head(25)

,title,english_title,romaji_title,genres,rating_anilist,rating_mal,episodes,status,format,season,...,source_material,popularity_anilist,mal_members,mal_rank,cover_image_url,start_date,end_date,duration_per_ep,age_rating,mal_id
0,Attack on Titan,Attack on Titan,Shingeki no Kyojin,Action | Drama | Fantasy | Mystery,8.5,8.57,25.0,FINISHED,TV,SPRING,...,MANGA,1000051,4367640.0,127.0,https://s4.anilist.co/file/anilistcdn/media/an...,2013-04-07,2013-09-28,24.0,R - 17+ (violence & profanity),16498.0
1,Demon Slayer: Kimetsu no Yaiba,Demon Slayer: Kimetsu no Yaiba,Kimetsu no Yaiba,Action | Adventure | Drama | Fantasy | Superna...,8.3,8.40,26.0,FINISHED,TV,SPRING,...,MANGA,946267,3455059.0,232.0,https://s4.anilist.co/file/anilistcdn/media/an...,2019-04-06,2019-09-28,24.0,R - 17+ (violence & profanity),38000.0
2,JUJUTSU KAISEN,JUJUTSU KAISEN,Jujutsu Kaisen,Action | Drama | Supernatural,8.4,8.50,24.0,FINISHED,TV,FALL,...,MANGA,915193,3043711.0,166.0,https://s4.anilist.co/file/anilistcdn/media/an...,2020-10-03,2021-03-27,24.0,R - 17+ (violence & profanity),40748.0
3,Death Note,Death Note,DEATH NOTE,Mystery | Psychological | Supernatural | Thriller,8.4,8.62,37.0,FINISHED,TV,FALL,...,MANGA,911296,4305882.0,99.0,https://s4.anilist.co/file/anilistcdn/media/an...,2006-10-04,2007-06-27,23.0,R - 17+ (violence & profanity),1535.0
4,My Hero Academia,My Hero Academia,Boku no Hero Academia,Action | Adventure | Comedy,7.7,7.83,13.0,FINISHED,TV,SPRING,...,MANGA,834900,3310857.0,1109.0,https://s4.anilist.co/file/anilistcdn/media/an...,2016-04-03,2016-06-26,24.0,PG-13 - Teens 13 or older,31964.0
5,Hunter x Hunter (2011),Hunter x Hunter (2011),HUNTER×HUNTER (2011),Action | Adventure | Fantasy,8.9,9.03,148.0,FINISHED,TV,FALL,...,MANGA,800313,3193956.0,9.0,https://s4.anilist.co/file/anilistcdn/media/an...,2011-10-02,2014-09-24,24.0,PG-13 - Teens 13 or older,11061.0
6,One-Punch Man,One-Punch Man,One Punch Man,Action | Comedy | Sci-Fi | Supernatural,8.3,8.47,12.0,FINISHED,TV,FALL,...,MANGA,736705,3524529.0,181.0,https://s4.anilist.co/file/anilistcdn/media/an...,2015-10-05,2015-12-21,24.0,R - 17+ (violence & profanity),30276.0
7,Tokyo Ghoul,Tokyo Ghoul,Tokyo Ghoul,Action | Drama | Horror | Mystery | Psychologi...,7.6,7.79,12.0,FINISHED,TV,SUMMER,...,MANGA,706177,3060595.0,1235.0,https://s4.anilist.co/file/anilistcdn/media/an...,2014-07-04,2014-09-19,24.0,R - 17+ (violence & profanity),22319.0
8,ONE PIECE,ONE PIECE,ONE PIECE,Action | Adventure | Comedy | Drama | Fantasy,8.7,8.73,1.0,RELEASING,TV,FALL,...,MANGA,704583,2686317.0,55.0,https://s4.anilist.co/file/anilistcdn/media/an...,1999-10-20,Ongoing,24.0,PG-13 - Teens 13 or older,21.0
9,Attack on Titan Season 2,Attack on Titan Season 2,Shingeki no Kyojin Season 2,Action | Drama | Fantasy | Mystery,8.5,8.54,12.0,FINISHED,TV,SPRING,...,MANGA,700446,3024897.0,145.0,https://s4.anilist.co/file/anilistcdn/media/an...,2017-04-01,2017-06-17,25.0,R - 17+ (violence & profanity),25777.0
10,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist: Brotherhood,Hagane no Renkinjutsushi: FULLMETAL ALCHEMIST,Action | Adventure | Drama | Fantasy,9.0,9.11,64.0,FINISHED,TV,SPRING,...,MANGA,693251,3688199.0,3.0,https://s4.anilist.co/file/anilistcdn/media/an...,2009-04-05,2010-07-04,25.0,R - 17+ (violence & profanity),5114.0
11,Naruto,Naruto,NARUTO,Action | Adventure | Comedy | Drama | Fantasy ...,8.0,8.02,220.0,FINISHED,TV,FALL,...,MANGA,689246,3122140.0,729.0,https://s4.anilist.co/file/anilistcdn/media/an...,2002-10-03,2007-02-08,23.0,PG-13 - Teens 13 or older,20.0
12,Sword Art Online,Sword Art Online,Sword Art Online,Action | Adventure | Fantasy | Romance,7.0,7.23,25.0,FINISHED,TV,SUMMER,...,LIGHT_NOVEL,686409,3304019.0,3875.0,https://s4.anilist.co/file/anilistcdn/media/an...,2012-07-08,2012-12-23,23.0,PG-13 - Teens 13 or older,11757.0
13,Your Name.,Your Name.,Kimi no Na wa.,Drama | Romance | Supernatural,8.6,8.82,1.0,FINISHED,MOVIE,SUMMER,...,ORIGINAL,679163,3032023.0,37.0,https://s4.anilist.co/file/anilistcdn/media/an...,2016-08-26,2016-08-26,107.0,PG-13 - Teens 13 or older,32281.0
14,A Silent Voice,A Silent Voice,Koe no Katachi,Drama | Romance | Slice of Life,8.8,8.93,1.0,FINISHED,MOVIE,SUMMER,...,MANGA,676253,2621300.0,20.0,https://s4.anilist.co/file/anilistcdn/media/an...,2016-09-17,2016-09-17,130.0,PG-13 - Teens 13 or older,28851.0
15,Attack on Titan Season 3,Attack on Titan Season 3,Shingeki no Kyojin Season 3,Action | Drama | Fantasy | Mystery,8.6,8.64,12.0,FINISHED,TV,SUMMER,...,MANGA,654994,2670983.0,91.0,https://s4.anilist.co/file/anilistcdn/media/an...,2018-07-23,2018-10-15,24.0,R - 17+ (violence & profanity),35760.0
16,My Hero Academia Season 2,My Hero Academia Season 2,Boku no Hero Academia 2,Action | Adventure | Comedy,8.0,8.05,25.0,FINISHED,TV,SPRING,...,MANGA,630108,2737334.0,675.0,https://s4.anilist.co/file/anilistcdn/media/an...,2017-04-01,2017-09-30,24.0,PG-13 - Teens 13 or older,33486.0
17,Attack on Titan Final Season,Attack on Titan Final Season,Shingeki no Kyojin: The Final Season,Action | Drama | Fantasy | Mystery,8.7,8.79,16.0,FINISHED,TV,WINTER,...,MANGA,612311,2294450.0,39.0,https://s4.anilist.co/file/anilistcdn/media/an...,2020-12-07,2021-03-29,24.0,R - 17+ (violence & profanity),40028.0
18,The Promised Neverland,The Promised Neverland,Yakusoku no Neverland,Drama | Fantasy | Horror | Mystery | Psycholog...,8.4,8.47,12.0,FINISHED,TV,WINTER,...,MANGA,609761,2158098.0,183.0,https://s4.anilist.co/file/anilistcdn/media/an...,2019-01-10,2019-03-29,23.0,R - 17+ (violence & profanity),37779.0
19,Assassination Classroom,Assassination Classroom,Ansatsu Kyoushitsu,Action | Comedy | Drama | Supernatural,7.9,8.07,22.0,FINISHED,TV,WINTER,...,MANGA,601325,2219005.0,644.0,https://s4.anilist.co/file/anilistcdn/media/an...,2015-01-10,2015-06-20,23.0,PG-13 - Teens 13 or older,24833.0
20,Mob Psycho 100,Mob Psycho 100,Mob Psycho 100,Action | Comedy | Drama | Psychological | Slic...,8.4,8.49,12.0,FINISHED,TV,SUMMER,...,MANGA,595943,2324769.0,172.0,https://s4.anilist.co/file/anilistcdn/media/an...,2016-07-12,2016-09-27,24.0,PG-13 - Teens 13 or older,32182.0
21,Chainsaw Man,Chainsaw Man,Chainsaw Man,Action | Drama | Horror | Supernatural,8.3,8.43,12.0,FINISHED,TV,FALL,...,MANGA,586646,1972319.0,200.0,https://s4.anilist.co/file/anilistcdn/media/an...,2022-10-12,2022-12-28,25.0,R - 17+ (violence & profanity),44511.0
22,Your lie in April,Your lie in April,Shigatsu wa Kimi no Uso,Drama | Music | Romance | Slice of Life,8.4,8.64,22.0,FINISHED,TV,FALL,...,MANGA,585219,2430183.0,90.0,https://s4.anilist.co/file/anilistcdn/media/an...,2014-10-10,2015-03-20,23.0,PG-13 - Teens 13 or older,23273.0
23,Re:ZERO -Starting Life in Another World-,Re:ZERO -Starting Life in Another World-,Re:Zero kara Hajimeru Isekai Seikatsu,Action | Adventure | Drama | Fantasy | Psychol...,8.1,8.25,25.0,FINISHED,TV,SPRING,...,LIGHT_NOVEL,583381,2464739.0,390.0,https://s4.anilist.co/file/anilistcdn/media/an...,2016-04-04,2016-09-19,25.0,R - 17+ (violence & profanity),31240.0
24,Attack on Titan Season 3 Part 2,Attack on Titan Season 3 Part 2,Shingeki no Kyojin Season 3 Part 2,Action | Drama | Fantasy | Mystery,9.0,9.05,10.0,FINISHED,TV,SPRING,...,MANGA,583065,2597760.0,8.0,https://s4.anilist.co/file/anilistcdn/media/an...,2019-04-29,2019-07-01,24.0,R - 17+ (violence & profanity),38524.0

In [42]:
Anime_df.isnull().sum()

title                 0
english_title         0
romaji_title          0
genres                0
rating_anilist        0
rating_mal            0
episodes              0
status                0
format                0
season                0
year                  0
synopsis              0
studio                0
source_material       0
popularity_anilist    0
mal_members           0
mal_rank              0
cover_image_url       0
start_date            0
end_date              0
duration_per_ep       0
age_rating            0
mal_id                0
dtype: int64

In [43]:
from google.colab import drive
drive.mount('/content/drive')

Anime_df.to_csv('/content/drive/MyDrive/clean_anime_data.csv', index=False)
print("Saved to Google Drive!")

Mounted at /content/drive
Saved to Google Drive!